-- ====================================================================
-- SQL Script: Crear tabla 'tipos_clases' y configurar políticas RLS
-- Ejecuta este script en el editor SQL de tu panel de Supabase.
-- ====================================================================

-- 1. Crear la tabla
CREATE TABLE IF NOT EXISTS public.tipos_clases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    duracion_predeterminada INTEGER NOT NULL DEFAULT 60,
    color TEXT NOT NULL DEFAULT '#EF4444',
    icono TEXT NOT NULL DEFAULT 'ph-person-simple-tai-chi',
    orden INTEGER NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Habilitar Seguridad de Nivel de Fila (RLS)
ALTER TABLE public.tipos_clases ENABLE ROW LEVEL SECURITY;

-- 3. Crear Políticas RLS
-- Permitir lectura pública a cualquier usuario (anon y authenticated)
DROP POLICY IF EXISTS "Allow public select" ON public.tipos_clases;
CREATE POLICY "Allow public select" 
ON public.tipos_clases 
FOR SELECT 
USING (true);

-- Permitir todas las operaciones a usuarios autenticados
DROP POLICY IF EXISTS "Allow all for authenticated users" ON public.tipos_clases;
CREATE POLICY "Allow all for authenticated users" 
ON public.tipos_clases 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- Permitir todas las operaciones a usuarios anónimos (si tu app no usa auth estricto para inserción cliente)
DROP POLICY IF EXISTS "Allow all for anonymous users" ON public.tipos_clases;
CREATE POLICY "Allow all for anonymous users" 
ON public.tipos_clases 
FOR ALL 
TO anon 
USING (true) 
WITH CHECK (true);

-- 4. Insertar datos iniciales de ejemplo
INSERT INTO public.tipos_clases (nombre, duracion_predeterminada, color, icono, orden, activo)
VALUES 
('Yoga Vinyasa', 60, '#3B82F6', 'ph-person-simple-tai-chi', 1, true),
('Pilates', 60, '#10B981', 'ph-person-simple-tai-chi', 2, true),
('Hatha Yoga', 75, '#F59E0B', 'ph-person-simple-tai-chi', 3, true),
('Meditación', 30, '#8B5CF6', 'ph-person-simple-tai-chi', 4, true)
ON CONFLICT (nombre) DO NOTHING;
