-- ====================================================================
-- SQL Script: Sincronización de Grupos Profesionales y Alumnos
-- Ejecuta este script en el editor SQL de tu panel de Supabase.
-- ====================================================================

-- 1. Crear la tabla de relaciones de grupos si no existe
CREATE TABLE IF NOT EXISTS public.grupos_profesionales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesional_id BIGINT NOT NULL REFERENCES public.profesionales(id) ON DELETE CASCADE,
    alumno_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(profesional_id, alumno_id)
);

-- 2. Habilitar Seguridad a Nivel de Fila (RLS) en grupos_profesionales
ALTER TABLE public.grupos_profesionales ENABLE ROW LEVEL SECURITY;

-- 3. Crear Políticas RLS para grupos_profesionales
DROP POLICY IF EXISTS "Allow public select for grupos_profesionales" ON public.grupos_profesionales;
CREATE POLICY "Allow public select for grupos_profesionales" 
ON public.grupos_profesionales 
FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Allow all for authenticated in grupos_profesionales" ON public.grupos_profesionales;
CREATE POLICY "Allow all for authenticated in grupos_profesionales" 
ON public.grupos_profesionales 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for anon in grupos_profesionales" ON public.grupos_profesionales;
CREATE POLICY "Allow all for anon in grupos_profesionales" 
ON public.grupos_profesionales 
FOR ALL 
TO anon 
USING (true) 
WITH CHECK (true);

-- 4. Función y Trigger para sincronizar automáticamente usuarios con rol 'profesor' o 'profesional' a la tabla 'profesionales'
CREATE OR REPLACE FUNCTION public.sync_profile_to_profesionales()
RETURNS TRIGGER AS $$
BEGIN
    -- Si el rol del perfil es 'profesor' o 'profesional'
    IF NEW.rol IN ('profesor', 'profesional') THEN
        -- Comprobar si ya existe un profesional con el mismo email
        IF NOT EXISTS (
            SELECT 1 FROM public.profesionales WHERE email = NEW.email
        ) THEN
            INSERT INTO public.profesionales (nombre, email, foto_url, especialidad, color)
            VALUES (
                COALESCE(NEW.nombre, 'Profesional'),
                NEW.email,
                NULL, -- La tabla profiles no contiene columna avatar_url
                'General',
                '#8c8658'
            );
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Crear el trigger en la tabla profiles
DROP TRIGGER IF EXISTS on_profile_role_sync ON public.profiles;
CREATE TRIGGER on_profile_role_sync
    AFTER INSERT OR UPDATE OF rol ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION public.sync_profile_to_profesionales();

-- 5. Realizar una sincronización inicial de los perfiles con rol 'profesor' o 'profesional' existentes
INSERT INTO public.profesionales (nombre, email, foto_url, especialidad, color)
SELECT 
    COALESCE(nombre, 'Profesional'), 
    email, 
    NULL, -- La tabla profiles no contiene columna avatar_url
    'General', 
    '#8c8658'
FROM public.profiles
WHERE rol IN ('profesor', 'profesional')
  AND email NOT IN (SELECT email FROM public.profesionales);
